name = "cloudflare-docker-proxy"
compatibility_date = "2024-08-18"
main = "src/index.js"

# Default environment configuration
vars = { MODE = "production", TARGET_UPSTREAM = "" }

# Development environment
[[env]]
name = "dev"
vars = { MODE = "debug", TARGET_UPSTREAM = "https://registry-1.docker.io" }
route = ""

[env.dev.dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

# Production environment
[[env]]
name = "production"
routes = [
  { pattern = "docker.iwaitu.net", custom_domain = true },
  { pattern = "quay.iwaitu.net", custom_domain = true },
  { pattern = "gcr.iwaitu.net", custom_domain = true },
  { pattern = "k8s-gcr.iwaitu.net", custom_domain = true },
  { pattern = "k8s.iwaitu.net", custom_domain = true },
  { pattern = "ghcr.iwaitu.net", custom_domain = true },
  { pattern = "cloudsmith.iwaitu.net", custom_domain = true },
]
vars = { MODE = "production", TARGET_UPSTREAM = "" }

# Staging environment
[[env]]
name = "staging"
route = { pattern = "docker-staging.lixd.xyz", custom_domain = true }
vars = { MODE = "staging", TARGET_UPSTREAM = "" }
